### ISSUE TITLE
issue with custom value syncing in "select type" fields

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-gf-integration-with-mautic#21]
![screenshot-localhost-2021 11 20-12_34_04](https://user-images.githubusercontent.com/63343498/142717864-05d10253-3ec3-4b53-984e-4195eb560a72.png)
![screenshot-localhost-2021 11 20-12_34_23](https://user-images.githubusercontent.com/63343498/142717866-7f312c0f-491a-4405-acb5-f82ca1591254.png)

**Comment by pranjalshukla-cedcoss** [comment]
This is not an issue because it was select field , so enter a valid value which is mapped in mautic select type custom field.

and rest i have fixed for only custom string issue .
