### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by kavya-cedcoss** [Makewebbetter/mwb-gf-integration-with-mautic#26]
1. update readme 
2. mwb-gf-integration-with-mautic.php updae main file 
version:           1.0.0-  1.0.1
Tested up to:      5.8.1- 5.8.2
also update version in line 82 
[mautic-org.xml.zip](https://github.com/Makewebbetter/mwb-gf-integration-with-mautic/files/7691742/mautic-org.xml.zip)

**Comment by pranjalshukla-cedcoss** [comment]
Resolved.
